export const PLACEDATA_LOADING_STARTED = 'PLACEDATA_LOADING_STARTED';
export const PLACEDATA_LOADED = 'PLACEDATA_LOADED';
export const PLACEDATA_CANT_BE_DOWNLOADED = 'PLACEDATA_CANT_BE_DOWNLOADED';
export const PLACEDATA_LOADING_COMPLETED = 'PLACEDATA_LOADING_COMPLETED';
export const NAVIGATE_TO_FEATUTE = 'NAVIGATE_TO_FEATUTE';
